# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours

  workflow_dispatch:  # Allows manual trigger from Actions tab

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks repo under $GITHUB_WORKSPACE

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LahaArnab  # Change to your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show Git Status (for debugging)
        run: git status

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The branch to store the generated files
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
